### ISSUE TITLE
No longer works with latest update

### ISSUE THREAD

**Issue by YiitCan** [TermaciousTrickocity/Extended-Weapon-Display#1]

**Comment by foco21** [comment]
Did you get any errors? If so, could you show them to me?

**Comment by YiitCan** [comment]
No errors my friend the FOV slider is the only thing working the others are not working.

**Comment by HybridsEgo** [comment]
Fixed for MCC v1.3385.0.0
https://github.com/TermaciousTrickocity/Extended-Weapon-Display/releases/tag/v1.0.1-Release

**Comment by YiitCan** [comment]
Thank you for the fix you madman love you bro
